[package]
name    = "karabiner-thunk"
version = "0.1.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]
repository = "https://github.com/feb29/karabiner"
license  = "MIT/Apache-2.0"
keywords = ["lazy", "thunk"]
description = "lazy evaluation for rust"

[dependencies]
karabiner-onetime = "0.1"