[package]
name    = "karabiner"
version = "0.1.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]

[workspace]
members = ["karabiner-onetime", "karabiner-thunk"]

[dependencies]
karabiner-onetime = { path = "karabiner-onetime" }
karabiner-thunk   = { path = "karabiner-thunk" }
