[package]
name    = "karabiner"
version = "0.1.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]

[workspace]
members = ["karabiner-justonce", "karabiner-thunk"]

[dependencies]
karabiner-justonce = { path = "karabiner-justonce" }
karabiner-thunk    = { path = "karabiner-thunk" }
