[package]
name    = "karabiner"
version = "0.1.0"
authors = ["Kohei Watanabe <xbeef29@gmail.com>"]

[workspace]
members = ["just_once", "thunk"]

[dependencies.just_once]
path = "just_once"

[dependencies.thunk]
path = "thunk"
